"""Mermaid renderings of the topology graph, written to `docs/topology/`.

Four views, because one diagram of everything is unreadable:

* **physical** — L1 links proven by CDP/LLDP, one subgraph per device;
* **vlan-<id>** — the L2 story of one VLAN: trunks, access ports, portgroups,
  VMs and the gateway;
* **storage** — VM -> datastore -> logical drive -> physical drives;
* **applications** — services, listening ports and certificates inside the
  guests, with the established dependencies between them (Phase 5; the file is
  only written when guest snapshots exist).

Every file carries a generated header; they are outputs, never edited by hand.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from infra_agent.correlate.checks import Finding
from infra_agent.correlate.model import EdgeKind, NodeKind, TopologyGraph, atomic_write, iso

GENERATED_MARK = "<!-- generated by infra_agent.correlate -- do not edit by hand -->"

_UNSAFE = re.compile(r"[^A-Za-z0-9_]")

_CLASS_DEFS = "\n".join(
    [
        "  classDef switch fill:#e8f0fe,stroke:#4a76c8,color:#12243d;",
        "  classDef firewall fill:#fdecea,stroke:#c0392b,color:#3d1210;",
        "  classDef host fill:#eafaf1,stroke:#27865b,color:#0f2e1f;",
        "  classDef bmc fill:#f4f0fa,stroke:#7d5ba6,color:#241633;",
        "  classDef unknown fill:#f2f2f2,stroke:#8a8a8a,color:#222222;",
        "  classDef guest fill:#fff8e1,stroke:#b08900,color:#33280a;",
        "  classDef external fill:#f7f7f7,stroke:#8a8a8a,color:#333333,stroke-dasharray:4 3;",
        "  classDef expiring fill:#fdecea,stroke:#c0392b,color:#3d1210;",
        "  classDef mgmt stroke:#b8860b,stroke-width:3px;",
    ]
)

#: A certificate inside this many days is drawn in the alerting colour, which is
#: the same threshold as `CertificateExpiringSoon` and the daily digest.
CERT_WARN_DAYS = 30


def _safe(node_id: str) -> str:
    return "n_" + _UNSAFE.sub("_", node_id)


def _text(label: Any) -> str:
    return str(label).replace('"', "'").replace("\n", " ")


def _role(graph: TopologyGraph, device_node: str) -> str:
    return (
        str(graph.node(device_node).get("role", "unknown")) if device_node in graph else "unknown"
    )


def _device_of(graph: TopologyGraph, node: str) -> str | None:
    device = graph.node(node).get("device")
    return f"device:{device}" if device else None


def _header(graph: TopologyGraph, title: str, subtitle: str = "") -> str:
    summary = graph.summary()
    lines = [
        GENERATED_MARK,
        f"<!-- graph built at {summary['built_at']}; "
        f"{summary['nodes']} nodes, {summary['edges']} edges -->",
        f"<!-- rendered at {iso(datetime.now(UTC))} -->",
        "",
        f"# {title}",
        "",
    ]
    if subtitle:
        lines += [subtitle, ""]
    return "\n".join(lines)


def render_physical(graph: TopologyGraph) -> str:
    """L1: every device with the ports that have a proven neighbour."""
    lines = ["graph LR"]
    interfaces: dict[str, set[str]] = {}
    for source, target, _data in graph.edges_of_kind(EdgeKind.l1_neighbor):
        for node in (source, target):
            owner = _device_of(graph, node)
            if owner:
                interfaces.setdefault(owner, set()).add(node)
    for device in sorted(interfaces):
        role = _role(graph, device)
        label = _text(graph.node(device).get("label", device))
        lines.append(f'  subgraph {_safe(device)}["{label} ({role})"]')
        for iface in sorted(interfaces[device]):
            data = graph.node(iface)
            name = _text(str(data.get("label", iface)).replace(f"{data.get('device')} ", ""))
            lines.append(f'    {_safe(iface)}["{name}"]')
        lines.append("  end")
    drawn: set[frozenset[str]] = set()
    for source, target, data in sorted(
        graph.edges_of_kind(EdgeKind.l1_neighbor), key=lambda e: (e[0], e[1])
    ):
        pair = frozenset({source, target})
        if pair in drawn or len(pair) != 2:
            continue
        drawn.add(pair)
        protocols = "/".join(data.get("protocols") or ["l1"])
        confidence = data.get("confidence", 0.0)
        lines.append(f'  {_safe(source)} ---|"{protocols} {confidence:.2f}"| {_safe(target)}')
    for device in sorted(interfaces):
        lines.append(f"  class {_safe(device)} {_role(graph, device)};")
    mgmt = [n for n in graph.mgmt_path_nodes() if any(n in v for v in interfaces.values())]
    if mgmt:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(mgmt))} mgmt;")
    lines.append(_CLASS_DEFS)
    return "\n".join(lines)


def render_vlan(graph: TopologyGraph, vlan: int) -> str:
    """L2 for one VLAN: carriers, gateway, portgroups and the VMs on it."""
    vlan_node = f"vlan:{vlan}"
    lines = ["graph LR"]
    if vlan_node not in graph:
        return "\n".join(lines + [f'  missing["VLAN {vlan} is not in the graph"]'])
    label = _text(graph.node(vlan_node).get("label", vlan_node))
    lines.append(f'  {_safe(vlan_node)}(["{label}"])')
    highlight: list[str] = [vlan_node] if graph.node(vlan_node).get("mgmt_path") else []

    for kind, arrow in (
        (EdgeKind.trunk_vlan, "trunk"),
        (EdgeKind.access_vlan, "access"),
        (EdgeKind.svi_for, "gateway"),
    ):
        for iface, _data in sorted(graph.in_edges(vlan_node, kind), key=lambda t: t[0]):
            data = graph.node(iface)
            lines.append(f'  {_safe(iface)}["{_text(data.get("label", iface))}"]')
            lines.append(f'  {_safe(iface)} ---|"{arrow}"| {_safe(vlan_node)}')
            if data.get("mgmt_path"):
                highlight.append(iface)

    for portgroup, _data in sorted(
        graph.in_edges(vlan_node, EdgeKind.portgroup_vlan), key=lambda t: t[0]
    ):
        pg = graph.node(portgroup)
        lines.append(f'  {_safe(portgroup)}[/"{_text(pg.get("label", portgroup))}"/]')
        lines.append(f"  {_safe(vlan_node)} --- {_safe(portgroup)}")
        if pg.get("mgmt_path"):
            highlight.append(portgroup)
        for vnic, _e in sorted(graph.in_edges(portgroup, EdgeKind.attached_to), key=lambda t: t[0]):
            owner = graph.node(vnic).get("vm")
            node = f"vm:{owner}" if owner else vnic
            if node not in graph:
                node = vnic
            lines.append(f'  {_safe(node)}(["{_text(graph.node(node).get("label", node))}"])')
            lines.append(f"  {_safe(portgroup)} --- {_safe(node)}")
            if graph.node(node).get("mgmt_path"):
                highlight.append(node)

    if highlight:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(set(highlight)))} mgmt;")
    lines.append(_CLASS_DEFS)
    return "\n".join(lines)


def render_storage(graph: TopologyGraph) -> str:
    """VM -> datastore -> iLO logical drive -> physical drives."""
    lines = ["graph LR"]
    drawn: set[str] = set()

    def node_line(node: str, shape: str = "[]") -> None:
        if node in drawn:
            return
        drawn.add(node)
        label = _text(graph.node(node).get("label", node))
        open_, close = shape[0], shape[1]
        lines.append(f'  {_safe(node)}{open_}"{label}"{close}')

    for datastore in graph.nodes_of_kind(NodeKind.datastore):
        node_line(datastore, "[]")
        for vm, _e in sorted(graph.in_edges(datastore, EdgeKind.stored_on), key=lambda t: t[0]):
            node_line(vm, "()")
            lines.append(f"  {_safe(vm)} --> {_safe(datastore)}")
        for logical, edge in sorted(
            graph.out_edges(datastore, EdgeKind.backed_by), key=lambda t: t[0]
        ):
            node_line(logical, "[]")
            volume = edge.get("volume_id") or ""
            suffix = f'|"{volume[:8]}"|' if volume else ""
            lines.append(f"  {_safe(datastore)} -->{suffix} {_safe(logical)}")
            for drive, _e in sorted(graph.out_edges(logical, EdgeKind.spans), key=lambda t: t[0]):
                node_line(drive, "()")
                lines.append(f"  {_safe(logical)} --> {_safe(drive)}")
    mgmt = [n for n in drawn if graph.node(n).get("mgmt_path")]
    if mgmt:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(mgmt))} mgmt;")
    lines.append(_CLASS_DEFS)
    return "\n".join(lines)


def render_applications(graph: TopologyGraph) -> str:
    """What each guest runs, on which port, and who depends on it.

    One subgraph per guest: the services it runs, the ports they answer on and
    the certificates those ports present. Arrows between subgraphs are
    established dependencies observed inside the guests, so a change on a port
    shows who calls it before anybody approves it.
    """
    lines = ["graph LR"]
    guests: dict[str, list[str]] = {}
    for node in graph.nodes_of_kind(NodeKind.service) + graph.nodes_of_kind(NodeKind.listener):
        owner = _application_owner(graph, node)
        if owner:
            guests.setdefault(owner, []).append(node)
    if not guests:
        return "\n".join(lines + ['  empty["No guest snapshots have been collected yet"]'])

    highlight: list[str] = []
    expiring: list[str] = []
    for owner in sorted(guests):
        label = _text(graph.node(owner).get("label", owner)) if owner in graph else owner
        lines.append(f'  subgraph {_safe(owner)}["{label}"]')
        for node in sorted(guests[owner]):
            data = graph.node(node)
            if data.get("kind") == str(NodeKind.service):
                lines.append(f'    {_safe(node)}(["{_text(data.get("service", node))}"])')
            else:
                port = f"{data.get('proto')}/{data.get('port')}"
                process = data.get("process")
                text = f"{port} {process}" if process else port
                lines.append(f'    {_safe(node)}["{_text(text)}"]')
            if data.get("mgmt_path"):
                highlight.append(node)
        lines.append("  end")

    drawn_certs: set[str] = set()
    for source, target, _data in sorted(
        graph.edges_of_kind(EdgeKind.listens_on), key=lambda e: (e[0], e[1])
    ):
        if source in graph and target in graph:
            lines.append(f"  {_safe(source)} --> {_safe(target)}")

    # Every certificate a port presents, plus any certificate on a guest that is
    # about to expire - the one nobody serves yet is exactly the one that gets
    # forgotten until it breaks something.
    for source, target, _data in sorted(
        graph.edges_of_kind(EdgeKind.has_certificate), key=lambda e: (e[0], e[1])
    ):
        cert = graph.node(target)
        days = cert.get("days_to_expiry")
        soon = isinstance(days, (int, float)) and days < CERT_WARN_DAYS
        served = graph.node(source).get("kind") == str(NodeKind.listener)
        if not served and not (soon and source in guests):
            continue
        if target not in drawn_certs:
            drawn_certs.add(target)
            suffix = f" ({days:.0f}d)" if isinstance(days, (int, float)) else ""
            lines.append(f'  {_safe(target)}[/"{_text(cert.get("subject", target))}{suffix}"/]')
            if soon:
                expiring.append(target)
        lines.append(f'  {_safe(source)} -.->|"tls"| {_safe(target)}')

    externals: list[str] = []
    # A node already drawn inside a subgraph, or that *is* a subgraph, must not
    # be declared again: mermaid gives an id one meaning only.
    drawn = {node for nodes in guests.values() for node in nodes} | set(guests)
    for source, target, data in sorted(
        graph.edges_of_kind(EdgeKind.connects_to), key=lambda e: (e[0], e[1])
    ):
        if graph.node(target).get("kind") == str(NodeKind.external_endpoint):
            if target not in externals:
                externals.append(target)
                lines.append(f'  {_safe(target)}["{_text(graph.node(target).get("label"))}"]')
        elif target not in drawn and target not in drawn_certs:
            drawn.add(target)
            label = _text(graph.node(target).get("label", target))
            lines.append(f'  {_safe(target)}["{label}"]')
        port = data.get("remote_port")
        arrow = f'|"{port}"|' if port else ""
        lines.append(f"  {_safe(source)} -->{arrow} {_safe(target)}")

    for owner in sorted(guests):
        lines.append(f"  class {_safe(owner)} guest;")
    if externals:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(set(externals)))} external;")
    if expiring:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(set(expiring)))} expiring;")
    if highlight:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(set(highlight)))} mgmt;")
    lines.append(_CLASS_DEFS)
    return "\n".join(lines)


def _application_owner(graph: TopologyGraph, node: str, depth: int = 0) -> str | None:
    """The vm or device a service or listener belongs to (listener -> service -> vm)."""
    if depth > 3:
        return None
    for kind in (EdgeKind.runs_service, EdgeKind.listens_on):
        for owner, _edge in graph.in_edges(node, kind):
            if graph.node(owner).get("kind") in (str(NodeKind.vm), str(NodeKind.device)):
                return owner
            grandparent = (
                _application_owner(graph, owner, depth + 1) if owner != node else None
            )
            if grandparent:
                return grandparent
    return None


def render(graph: TopologyGraph, diagram: str = "physical", vlan: int | None = None) -> str:
    """`physical`, `storage`, `applications` or `vlan` (with `vlan=<id>`)."""
    if diagram == "physical":
        return render_physical(graph)
    if diagram == "storage":
        return render_storage(graph)
    if diagram == "applications":
        return render_applications(graph)
    if diagram == "vlan":
        if vlan is None:
            raise ValueError("the vlan diagram needs a vlan id")
        return render_vlan(graph, vlan)
    raise ValueError(f"unknown diagram {diagram!r}: use physical, vlan, storage or applications")


def _fence(mermaid: str) -> str:
    return f"```mermaid\n{mermaid}\n```\n"


def _findings_section(findings: list[Finding]) -> str:
    if not findings:
        return "No consistency findings.\n"
    lines = ["| Severity | Finding |", "|---|---|"]
    lines += [f"| {f.severity} | {f.title} |" for f in findings]
    return "\n".join(lines) + "\n"


def write_docs(
    graph: TopologyGraph,
    directory: Path,
    findings: list[Finding] | None = None,
    max_vlans: int = 24,
) -> list[Path]:
    """Render every view into `directory` and return the files written."""
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    physical = directory / "physical.md"
    atomic_write(
        physical,
        _header(
            graph,
            "Physical topology (L1)",
            "Links proven by CDP/LLDP. The label is the protocol and the "
            "confidence; a gold border marks the platform's own path.",
        )
        + _fence(render_physical(graph)),
    )
    written.append(physical)

    storage = directory / "storage.md"
    atomic_write(
        storage,
        _header(
            graph,
            "Storage chain",
            "VM to VMDK datastore to iLO logical drive to physical drives.",
        )
        + _fence(render_storage(graph)),
    )
    written.append(storage)

    if graph.nodes_of_kind(NodeKind.service) or graph.nodes_of_kind(NodeKind.listener):
        applications = directory / "applications.md"
        atomic_write(
            applications,
            _header(
                graph,
                "Applications and dependencies",
                "Services and listening ports inside the guests, with the "
                "established connections between them. Dashed nodes are outside "
                "the estate; a red certificate expires within 30 days.",
            )
            + _fence(render_applications(graph)),
        )
        written.append(applications)

    vlans = sorted(
        int(graph.node(v).get("vlan_id", 0)) for v in graph.nodes_of_kind(NodeKind.vlan)
    )[:max_vlans]
    for vlan in vlans:
        path = directory / f"vlan-{vlan:04d}.md"
        atomic_write(
            path,
            _header(graph, f"VLAN {vlan} (L2)", "Carriers, gateway, portgroups and VMs.")
            + _fence(render_vlan(graph, vlan)),
        )
        written.append(path)

    index = directory / "index.md"
    index_lines = [
        _header(graph, "Topology index", "Generated by `infra graph render`."),
        "| View | File |",
        "|---|---|",
        "| Physical (L1) | [physical.md](physical.md) |",
        "| Storage | [storage.md](storage.md) |",
    ]
    if (directory / "applications.md") in written:
        index_lines.append("| Applications | [applications.md](applications.md) |")
    index_lines += [f"| VLAN {v} | [vlan-{v:04d}.md](vlan-{v:04d}.md) |" for v in vlans]
    index_lines += ["", "## Consistency findings", "", _findings_section(findings or [])]
    atomic_write(index, "\n".join(index_lines))
    written.append(index)
    return written
