"""Mermaid renderings of the topology graph, written to `docs/topology/`.

Three views, because one diagram of everything is unreadable:

* **physical** — L1 links proven by CDP/LLDP, one subgraph per device;
* **vlan-<id>** — the L2 story of one VLAN: trunks, access ports, portgroups,
  VMs and the gateway;
* **storage** — VM -> datastore -> logical drive -> physical drives.

Every file carries a generated header; they are outputs, never edited by hand.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from infra_agent.correlate.checks import Finding
from infra_agent.correlate.model import EdgeKind, NodeKind, TopologyGraph, iso

GENERATED_MARK = "<!-- generated by infra_agent.correlate -- do not edit by hand -->"

_UNSAFE = re.compile(r"[^A-Za-z0-9_]")

_CLASS_DEFS = "\n".join(
    [
        "  classDef switch fill:#e8f0fe,stroke:#4a76c8,color:#12243d;",
        "  classDef firewall fill:#fdecea,stroke:#c0392b,color:#3d1210;",
        "  classDef host fill:#eafaf1,stroke:#27865b,color:#0f2e1f;",
        "  classDef bmc fill:#f4f0fa,stroke:#7d5ba6,color:#241633;",
        "  classDef unknown fill:#f2f2f2,stroke:#8a8a8a,color:#222222;",
        "  classDef mgmt stroke:#b8860b,stroke-width:3px;",
    ]
)


def _safe(node_id: str) -> str:
    return "n_" + _UNSAFE.sub("_", node_id)


def _text(label: Any) -> str:
    return str(label).replace('"', "'").replace("\n", " ")


def _role(graph: TopologyGraph, device_node: str) -> str:
    return (
        str(graph.node(device_node).get("role", "unknown")) if device_node in graph else "unknown"
    )


def _device_of(graph: TopologyGraph, node: str) -> str | None:
    device = graph.node(node).get("device")
    return f"device:{device}" if device else None


def _header(graph: TopologyGraph, title: str, subtitle: str = "") -> str:
    summary = graph.summary()
    lines = [
        GENERATED_MARK,
        f"<!-- graph built at {summary['built_at']}; "
        f"{summary['nodes']} nodes, {summary['edges']} edges -->",
        f"<!-- rendered at {iso(datetime.now(UTC))} -->",
        "",
        f"# {title}",
        "",
    ]
    if subtitle:
        lines += [subtitle, ""]
    return "\n".join(lines)


def render_physical(graph: TopologyGraph) -> str:
    """L1: every device with the ports that have a proven neighbour."""
    lines = ["graph LR"]
    interfaces: dict[str, set[str]] = {}
    for source, target, _data in graph.edges_of_kind(EdgeKind.l1_neighbor):
        for node in (source, target):
            owner = _device_of(graph, node)
            if owner:
                interfaces.setdefault(owner, set()).add(node)
    for device in sorted(interfaces):
        role = _role(graph, device)
        label = _text(graph.node(device).get("label", device))
        lines.append(f'  subgraph {_safe(device)}["{label} ({role})"]')
        for iface in sorted(interfaces[device]):
            data = graph.node(iface)
            name = _text(str(data.get("label", iface)).replace(f"{data.get('device')} ", ""))
            lines.append(f'    {_safe(iface)}["{name}"]')
        lines.append("  end")
    drawn: set[frozenset[str]] = set()
    for source, target, data in sorted(
        graph.edges_of_kind(EdgeKind.l1_neighbor), key=lambda e: (e[0], e[1])
    ):
        pair = frozenset({source, target})
        if pair in drawn or len(pair) != 2:
            continue
        drawn.add(pair)
        protocols = "/".join(data.get("protocols") or ["l1"])
        confidence = data.get("confidence", 0.0)
        lines.append(f'  {_safe(source)} ---|"{protocols} {confidence:.2f}"| {_safe(target)}')
    for device in sorted(interfaces):
        lines.append(f"  class {_safe(device)} {_role(graph, device)};")
    mgmt = [n for n in graph.mgmt_path_nodes() if any(n in v for v in interfaces.values())]
    if mgmt:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(mgmt))} mgmt;")
    lines.append(_CLASS_DEFS)
    return "\n".join(lines)


def render_vlan(graph: TopologyGraph, vlan: int) -> str:
    """L2 for one VLAN: carriers, gateway, portgroups and the VMs on it."""
    vlan_node = f"vlan:{vlan}"
    lines = ["graph LR"]
    if vlan_node not in graph:
        return "\n".join(lines + [f'  missing["VLAN {vlan} is not in the graph"]'])
    label = _text(graph.node(vlan_node).get("label", vlan_node))
    lines.append(f'  {_safe(vlan_node)}(["{label}"])')
    highlight: list[str] = [vlan_node] if graph.node(vlan_node).get("mgmt_path") else []

    for kind, arrow in (
        (EdgeKind.trunk_vlan, "trunk"),
        (EdgeKind.access_vlan, "access"),
        (EdgeKind.svi_for, "gateway"),
    ):
        for iface, _data in sorted(graph.in_edges(vlan_node, kind), key=lambda t: t[0]):
            data = graph.node(iface)
            lines.append(f'  {_safe(iface)}["{_text(data.get("label", iface))}"]')
            lines.append(f'  {_safe(iface)} ---|"{arrow}"| {_safe(vlan_node)}')
            if data.get("mgmt_path"):
                highlight.append(iface)

    for portgroup, _data in sorted(
        graph.in_edges(vlan_node, EdgeKind.portgroup_vlan), key=lambda t: t[0]
    ):
        pg = graph.node(portgroup)
        lines.append(f'  {_safe(portgroup)}[/"{_text(pg.get("label", portgroup))}"/]')
        lines.append(f"  {_safe(vlan_node)} --- {_safe(portgroup)}")
        if pg.get("mgmt_path"):
            highlight.append(portgroup)
        for vnic, _e in sorted(graph.in_edges(portgroup, EdgeKind.attached_to), key=lambda t: t[0]):
            owner = graph.node(vnic).get("vm")
            node = f"vm:{owner}" if owner else vnic
            if node not in graph:
                node = vnic
            lines.append(f'  {_safe(node)}(["{_text(graph.node(node).get("label", node))}"])')
            lines.append(f"  {_safe(portgroup)} --- {_safe(node)}")
            if graph.node(node).get("mgmt_path"):
                highlight.append(node)

    if highlight:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(set(highlight)))} mgmt;")
    lines.append(_CLASS_DEFS)
    return "\n".join(lines)


def render_storage(graph: TopologyGraph) -> str:
    """VM -> datastore -> iLO logical drive -> physical drives."""
    lines = ["graph LR"]
    drawn: set[str] = set()

    def node_line(node: str, shape: str = "[]") -> None:
        if node in drawn:
            return
        drawn.add(node)
        label = _text(graph.node(node).get("label", node))
        open_, close = shape[0], shape[1]
        lines.append(f'  {_safe(node)}{open_}"{label}"{close}')

    for datastore in graph.nodes_of_kind(NodeKind.datastore):
        node_line(datastore, "[]")
        for vm, _e in sorted(graph.in_edges(datastore, EdgeKind.stored_on), key=lambda t: t[0]):
            node_line(vm, "()")
            lines.append(f"  {_safe(vm)} --> {_safe(datastore)}")
        for logical, edge in sorted(
            graph.out_edges(datastore, EdgeKind.backed_by), key=lambda t: t[0]
        ):
            node_line(logical, "[]")
            volume = edge.get("volume_id") or ""
            suffix = f'|"{volume[:8]}"|' if volume else ""
            lines.append(f"  {_safe(datastore)} -->{suffix} {_safe(logical)}")
            for drive, _e in sorted(graph.out_edges(logical, EdgeKind.spans), key=lambda t: t[0]):
                node_line(drive, "()")
                lines.append(f"  {_safe(logical)} --> {_safe(drive)}")
    mgmt = [n for n in drawn if graph.node(n).get("mgmt_path")]
    if mgmt:
        lines.append(f"  class {','.join(_safe(n) for n in sorted(mgmt))} mgmt;")
    lines.append(_CLASS_DEFS)
    return "\n".join(lines)


def render(graph: TopologyGraph, diagram: str = "physical", vlan: int | None = None) -> str:
    """`physical`, `storage` or `vlan` (with `vlan=<id>`)."""
    if diagram == "physical":
        return render_physical(graph)
    if diagram == "storage":
        return render_storage(graph)
    if diagram == "vlan":
        if vlan is None:
            raise ValueError("the vlan diagram needs a vlan id")
        return render_vlan(graph, vlan)
    raise ValueError(f"unknown diagram {diagram!r}: use physical, vlan or storage")


def _fence(mermaid: str) -> str:
    return f"```mermaid\n{mermaid}\n```\n"


def _findings_section(findings: list[Finding]) -> str:
    if not findings:
        return "No consistency findings.\n"
    lines = ["| Severity | Finding |", "|---|---|"]
    lines += [f"| {f.severity} | {f.title} |" for f in findings]
    return "\n".join(lines) + "\n"


def write_docs(
    graph: TopologyGraph,
    directory: Path,
    findings: list[Finding] | None = None,
    max_vlans: int = 24,
) -> list[Path]:
    """Render every view into `directory` and return the files written."""
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    physical = directory / "physical.md"
    physical.write_text(
        _header(
            graph,
            "Physical topology (L1)",
            "Links proven by CDP/LLDP. The label is the protocol and the "
            "confidence; a gold border marks the platform's own path.",
        )
        + _fence(render_physical(graph))
    )
    written.append(physical)

    storage = directory / "storage.md"
    storage.write_text(
        _header(
            graph,
            "Storage chain",
            "VM to VMDK datastore to iLO logical drive to physical drives.",
        )
        + _fence(render_storage(graph))
    )
    written.append(storage)

    vlans = sorted(
        int(graph.node(v).get("vlan_id", 0)) for v in graph.nodes_of_kind(NodeKind.vlan)
    )[:max_vlans]
    for vlan in vlans:
        path = directory / f"vlan-{vlan:04d}.md"
        path.write_text(
            _header(graph, f"VLAN {vlan} (L2)", "Carriers, gateway, portgroups and VMs.")
            + _fence(render_vlan(graph, vlan))
        )
        written.append(path)

    index = directory / "index.md"
    index_lines = [
        _header(graph, "Topology index", "Generated by `infra graph render`."),
        "| View | File |",
        "|---|---|",
        "| Physical (L1) | [physical.md](physical.md) |",
        "| Storage | [storage.md](storage.md) |",
    ]
    index_lines += [f"| VLAN {v} | [vlan-{v:04d}.md](vlan-{v:04d}.md) |" for v in vlans]
    index_lines += ["", "## Consistency findings", "", _findings_section(findings or [])]
    index.write_text("\n".join(index_lines))
    written.append(index)
    return written
