"""Guests, from the ESXi snapshots into the seed inventory and out to the tools.

Three jobs, all of them file generation - nothing here talks to a guest:

1. **Discovery.** `guest_candidates` reads the latest ESXi snapshots and offers
   the VMs that could be onboarded as guests: a VM whose guest IP is known and
   whose annotation (the Notes field, the only place a standalone ESXi host will
   keep a tag without vCenter) carries `guest:linux` or `guest:windows`. This is
   what `infra onboard seed-guests` walks the owner through.
2. **Ansible.** `write_ansible_inventory` writes `ansible/inventory/guests.yml`
   from the seed inventory, so the `node_exporter` / `windows_exporter`
   playbooks run against exactly the guests the platform knows about. No
   credential is ever written into it: secrets live in SOPS and are passed to
   `ansible-playbook` by the operator (see `ansible/README.md`).
3. **Prometheus.** `write_prometheus_targets` writes
   `deploy/prometheus/targets/guests.json` for the `guests` file_sd job, which
   is how the exporters installed by those playbooks get scraped.

The generated files are outputs: they are rewritten wholesale and carry a
header saying so.
"""

from __future__ import annotations

import ipaddress
import json
import re
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field

from infra_agent.config import Settings, get_settings
from infra_agent.models.common import DeviceKind, SeedDevice, SeedInventory
from infra_agent.store.snapshots import FileSnapshotStore

#: Where the generated files land, relative to the repository root.
ANSIBLE_INVENTORY = Path("ansible/inventory/guests.yml")
PROMETHEUS_TARGETS = Path("deploy/prometheus/targets/guests.json")

#: The exporters `ansible/playbooks/` installs.
NODE_EXPORTER_PORT = 9100
WINDOWS_EXPORTER_PORT = 9182

GENERATED_HEADER = (
    "# generated by `infra onboard seed-guests` (infra_agent/guest_inventory.py)\n"
    "# do not edit by hand: it is rewritten from inventory/seed.yaml\n"
)

#: An annotation token that says this VM is a guest worth onboarding.
GUEST_KIND_TAGS: dict[str, DeviceKind] = {
    "guest:linux": DeviceKind.guest_linux,
    "guest:windows": DeviceKind.guest_windows,
}

#: `service:nginx`, `auto:restart`, `vm:web-01` - the tags the collector and the
#: change engine read. Copied from the annotation onto the seed device.
#:
#: The *key* is matched case-insensitively and normalised to lower case, but the
#: value keeps the case the operator typed: `vm:Web-01` has to match the graph's
#: `vm:Web-01` node id, and a Windows service really is called `MSSQLSERVER`.
_TAG = re.compile(r"\b([A-Za-z][A-Za-z0-9_-]*):([A-Za-z0-9_.@+-]+)\b")

EXPORTER_PORTS: dict[DeviceKind, int] = {
    DeviceKind.guest_linux: NODE_EXPORTER_PORT,
    DeviceKind.guest_windows: WINDOWS_EXPORTER_PORT,
}

GUEST_KINDS = tuple(EXPORTER_PORTS)


class GuestCandidate(BaseModel):
    """A VM that could be onboarded as a guest."""

    vm: str
    host: str
    kind: DeviceKind
    address: str
    tags: list[str] = Field(default_factory=list)
    power_state: str | None = None
    guest_os: str | None = None
    onboarded: bool = False
    reason: str = ""

    @property
    def suggested_name(self) -> str:
        return self.vm


def annotation_tags(*values: Any) -> list[str]:
    """`key:value` tokens out of a VM annotation or an explicit tag list.

    The key is lower-cased so `Service:nginx` and `service:nginx` are one tag;
    the value is left exactly as written, because it is a name somewhere else -
    a VM node id (`vm:Web-01`), a Windows service (`service:MSSQLSERVER`).
    """
    found: list[str] = []
    for value in values:
        if isinstance(value, (list, tuple)):
            found.extend(str(item) for item in value)
        elif value:
            found.extend(f"{key.lower()}:{val}" for key, val in _TAG.findall(str(value)))
    return sorted(dict.fromkeys(tag.strip() for tag in found if tag.strip()))


def guest_kind(tags: list[str]) -> DeviceKind | None:
    for tag in tags:
        kind = GUEST_KIND_TAGS.get(tag.lower())
        if kind is not None:
            return kind
    return None


def usable_address(addresses: Any) -> str | None:
    """The first address a collector could actually connect to.

    APIPA, loopback and IPv6 link-local addresses are what VMware Tools reports
    when the guest has no lease; connecting to one would fail every cycle.
    """
    for value in addresses or []:
        try:
            parsed = ipaddress.ip_address(str(value))
        except ValueError:
            continue
        if parsed.is_loopback or parsed.is_link_local or parsed.is_multicast:
            continue
        if parsed.version == 4:
            return str(parsed)
    return None


def guest_candidates(store: FileSnapshotStore, inventory: SeedInventory) -> list[GuestCandidate]:
    """VMs from the latest ESXi snapshots that carry a `guest:` tag and an IP.

    Everything is offered, including the VMs already onboarded (marked
    `onboarded`) and the ones that cannot be reached yet (with the reason), so
    the owner sees why a VM they expected is missing instead of an empty list.
    """
    known = {device.name for device in inventory.devices}
    addresses = {device.mgmt_ip for device in inventory.devices}
    rows: list[GuestCandidate] = []
    for device in inventory.devices:
        if device.kind is not DeviceKind.esxi:
            continue
        snapshot = store.latest(device.name, "esxi")
        if snapshot is None:
            continue
        for vm in snapshot.data.get("vms") or []:
            if not isinstance(vm, dict):
                continue
            candidate = _candidate(device.name, vm, known, addresses)
            if candidate is not None:
                rows.append(candidate)
    rows.sort(key=lambda row: (row.host, row.vm))
    return rows


def _candidate(
    host: str, vm: dict[str, Any], known: set[str], addresses: set[str]
) -> GuestCandidate | None:
    name = str(vm.get("name") or "").strip()
    tags = annotation_tags(vm.get("annotation"), vm.get("tags"), vm.get("notes"))
    kind = guest_kind(tags)
    if not name or kind is None:
        return None
    ips = list(vm.get("guest_ips") or [])
    for nic in vm.get("nics") or vm.get("vnics") or []:
        if isinstance(nic, dict):
            ips.extend(nic.get("ips") or nic.get("ip_addresses") or [])
    address = usable_address(ips)
    onboarded = name in known or (address is not None and address in addresses)
    reason = ""
    if address is None:
        reason = "no usable IPv4 address in the snapshot (VMware Tools may not be running)"
    elif onboarded:
        reason = "already in the seed inventory"
    return GuestCandidate(
        vm=name,
        host=host,
        kind=kind,
        address=address or "",
        tags=[tag for tag in tags if tag.lower() not in GUEST_KIND_TAGS],
        power_state=vm.get("power_state"),
        guest_os=vm.get("guest_os"),
        onboarded=onboarded,
        reason=reason,
    )


def seed_device_for(candidate: GuestCandidate, name: str | None = None) -> SeedDevice:
    """The seed entry for a candidate, carrying the tags from its annotation."""
    tags = sorted({*candidate.tags, f"vm:{candidate.vm}", f"host:{candidate.host}"})
    return SeedDevice(
        name=name or candidate.suggested_name,
        kind=candidate.kind,
        mgmt_ip=candidate.address,
        credential_ref=name or candidate.suggested_name,
        tags=tags,
        notes=f"guest discovered on {candidate.host}",
    )


# ---------------------------------------------------------------------------
# generated files
# ---------------------------------------------------------------------------
def guests_of(inventory: SeedInventory) -> list[SeedDevice]:
    return sorted(
        (device for device in inventory.devices if device.kind in GUEST_KINDS),
        key=lambda device: device.name,
    )


def ansible_inventory(inventory: SeedInventory) -> dict[str, Any]:
    """The Ansible inventory as data, so it can be asserted without a file.

    Connection settings only: no user, no password, no key path. The playbooks
    are run by a human with `--user` / `--private-key` or a vault, because this
    file is committed and the platform's secrets live in SOPS.
    """
    groups: dict[str, dict[str, Any]] = {
        "guest_linux": {
            "hosts": {},
            "vars": {
                "ansible_connection": "ssh",
                "ansible_python_interpreter": "auto_silent",
                "exporter_port": NODE_EXPORTER_PORT,
            },
        },
        "guest_windows": {
            "hosts": {},
            "vars": {
                "ansible_connection": "winrm",
                "ansible_port": 5986,
                "ansible_winrm_transport": "ntlm",
                "ansible_winrm_scheme": "https",
                "ansible_winrm_server_cert_validation": "ignore",
                "exporter_port": WINDOWS_EXPORTER_PORT,
            },
        },
    }
    for device in guests_of(inventory):
        group = groups[device.kind.value]
        host: dict[str, Any] = {"ansible_host": device.mgmt_ip}
        if device.kind is DeviceKind.guest_linux and device.port:
            host["ansible_port"] = device.port
        if device.tags:
            host["infra_tags"] = list(device.tags)
        group["hosts"][device.name] = host
    return {"all": {"children": groups}}


def prometheus_targets(inventory: SeedInventory) -> list[dict[str, Any]]:
    """file_sd rows for the `guests` scrape job, one target per guest."""
    rows: list[dict[str, Any]] = []
    for device in guests_of(inventory):
        port = EXPORTER_PORTS[device.kind]
        rows.append(
            {
                "targets": [f"{device.mgmt_ip}:{port}"],
                "labels": {
                    "device": device.name,
                    "platform": "guest",
                    "os": "windows" if device.kind is DeviceKind.guest_windows else "linux",
                    "exporter": (
                        "windows_exporter"
                        if device.kind is DeviceKind.guest_windows
                        else "node_exporter"
                    ),
                },
            }
        )
    return rows


def _write(path: Path, text: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path


def write_ansible_inventory(inventory: SeedInventory, path: Path | None = None) -> Path:
    target = path or ANSIBLE_INVENTORY
    body = yaml.safe_dump(ansible_inventory(inventory), sort_keys=False, default_flow_style=False)
    return _write(target, GENERATED_HEADER + body)


def write_prometheus_targets(inventory: SeedInventory, path: Path | None = None) -> Path:
    target = path or PROMETHEUS_TARGETS
    # file_sd is JSON, which has no comments: the header lives in a label-free
    # first entry nowhere, so the note goes in the file name and the docs.
    return _write(target, json.dumps(prometheus_targets(inventory), indent=1) + "\n")


def write_all(
    inventory: SeedInventory | None = None,
    settings: Settings | None = None,
    *,
    root: Path | None = None,
) -> list[Path]:
    """Rewrite both generated files; returns what was written."""
    settings = settings or get_settings()
    inventory = inventory if inventory is not None else SeedInventory.load(settings.seed_inventory)
    base = root or Path.cwd()
    return [
        write_ansible_inventory(inventory, base / ANSIBLE_INVENTORY),
        write_prometheus_targets(inventory, base / PROMETHEUS_TARGETS),
    ]
